### ISSUE TITLE
"getting started" cards too big on medium-width screen

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/operators.urbit.org#15]
they render ok on mobile size and on full size but they look like this when the browser is split-screen tiled:

![2022-06-30_12h46m16s](https://user-images.githubusercontent.com/77721746/176569489-d6c86006-1379-4b61-aaad-6b8ac6c09819.png)

**Comment by matildepark** [comment]
Not a bug, this is how it’s always been on all sites
